version: "3.8"

services:
  web:
    build:
      context: ./app
      dockerfile: Dockerfile.prod
    command: gunicorn professional_website.wsgi:application --bind 0.0.0.0:8000
    expose:
      - 8000
    env_file:
      - ./.env.prod
    depends_on:
      - db
  nginx:
    build: ./nginx
    ports:
      - 1337:80
    depends_on:
      - web
  db:
    image: mysql:5.7
    build: ./mysql/
    ports:
      - 8001:3306
    restart: always
    env_file:
      - ./.env.prod.db
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql-init.sql:/tmp/mysql-init.sql
volumes:
  mysql_data: {}
