version: "3.8"

services:
  web:
    build: ./app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: mysql:5.7
    build: ./mysql/
    ports:
      - 8001:3306
    restart: always
    environment:
      MYSQL_DATABASE: professional_website
      MYSQL_USER: root
      MYSQL_PASSWORD: 9999
      MYSQL_ROOT_PASSWORD: 9999
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql-init.sql:/tmp/mysql-init.sql
volumes:
  mysql_data: {}
